import "./prototypes/controls"
import "./prototypes/error-entity"
import "./prototypes/sprites"
import "./prototypes/styles"
import "./prototypes/tips-and-tricks"
import "./prototypes/tools-and-shortcuts"
