// Generated by gen-locale-defs.ts
// noinspection JSUnusedGlobalSymbols

export declare const enum L_ItemName {
  /** Assembly Creation Tool */
  B2p2AssemblyCreationTool = "item-name.b2p2:assembly-creation-tool",
  /** Import Preview blueprint */
  B2p2ImportPreview = "item-name.b2p2:import-preview",
  /** Import Preview metadata */
  B2p2ImportPreviewPositionMarker = "item-name.b2p2:ImportPreviewPositionMarker",
}
export declare const enum L_ModSettingName {
  /** Auto-save assemblies [img=info] */
  B2p2AutoSave = "mod-setting-name.b2p2:auto-save",
}
export declare const enum L_ModSettingDescription {
  /** Automatically attempt to save when leaving an assembly. */
  B2p2AutoSave = "mod-setting-description.b2p2:auto-save",
}
export declare const enum L_Controls {
  /** Teleport backward */
  B2p2TeleportBackward = "controls.b2p2:teleport-backward",
  /** Teleport forward */
  B2p2TeleportForward = "controls.b2p2:teleport-forward",
  /** Teleport to entity at source assembly */
  B2p2TeleportToSource = "controls.b2p2:teleport-to-source",
  /** Create new assembly */
  B2p2CreateAssembly = "controls.b2p2:create-assembly",
}
export declare const enum L_ShortcutName {
  /** b2p2: New assembly */
  B2p2CreateAssembly = "shortcut-name.b2p2:create-assembly",
}
export declare const enum L_B2p2 {
  /** [entity=__1__] */
  EntityPicture = "b2p2.entity-picture",
  /** __1__x[item=__2__] */
  ItemCountPicture = "b2p2.item-count-picture",
  /** <None> */
  NoItems = "b2p2.no-items",
}
export declare const enum L_Diagnostic {
  /** [color=red]Collisions:[/color] */
  Overlap = "b2p2.diagnostic.overlap",
  /** __1__ could not be pasted */
  OverlapItem = "b2p2.diagnostic.overlap-item",
  /** [color=purple]Upgrades:[/color] [img=info] */
  CannotUpgrade = "b2p2.diagnostic.cannot-upgrade",
  /** Upgrades/fast-replace cannot be affected by blueprinting. To allow this, enable "Allow upgrades" in the the import additional settings. */
  CannotUpgradeTooltip = "b2p2.diagnostic.cannot-upgrade-tooltip",
  /** __1__: upgraded from __2__ */
  CannotUpgradeItem = "b2p2.diagnostic.cannot-upgrade-item",
  /** [color=yellow]Item requests changes:[/color] */
  ItemsIgnored = "b2p2.diagnostic.items-ignored",
  /** Changes in item requests will have no effect on paste. */
  ItemsIgnoredTooltip = "b2p2.diagnostic.items-ignored-tooltip",
  /** __1__: __2__  ->  __3__ */
  ItemsIgnoredItem = "b2p2.diagnostic.items-ignored-item",
  /** [font=default-bold]Click[/font] to teleport to the entity. */
  BasicTooltip = "b2p2.diagnostic.basic-tooltip",
  /** [font=default-bold]Click[/font] to teleport to the entity.\n[font=default-bold]Control click[/font] to teleport to entity at the [font=default-bold]import source[/font]. */
  TooltipWithAltLocation = "b2p2.diagnostic.tooltip-with-alt-location",
}
export declare const enum L_Interaction {
  /** An unexpected error occurred: __1__. Additional details outputted to log. Please report this to the mod author! */
  UnexpectedError = "b2p2.interaction.unexpected-error",
  /** __1__ */
  TranslateDialogueMessage = "b2p2.interaction.translate-dialogue-message",
  /** This area intersects with an existing assembly: __1__ */
  IntersectsExistingAssembly = "b2p2.interaction.intersects-existing-assembly",
  /** The import does not intersect with the target assembly at this location. */
  ImportDoesNotIntersectAssembly = "b2p2.interaction.import-does-not-intersect-assembly",
  /** The source or target assembly no longer exists. */
  ImportNoLongerValid = "b2p2.interaction.import-no-longer-valid",
  /** Flipped or rotated imports are currently not supported. */
  CannotFlipOrRotateImport = "b2p2.interaction.cannot-flip-or-rotate-import",
  /** An import from "__1__" was created on "__2__". */
  ImportCreated = "b2p2.interaction.import-created",
  /** This import has no source assembly. */
  ImportHasNoSource = "b2p2.interaction.import-has-no-source",
  /** Assembly saved\n  [font=default-bold]__1__[/font] entities */
  AssemblySaved = "b2p2.interaction.assembly-saved",
  /** Paste conflicts found after reset. */
  FoundPasteConflicts = "b2p2.interaction.found-paste-conflicts",
  /** Autosave: Failed to save assembly "__1__" as it has paste conflicts. */
  AutosaveFailedHasConflicts = "b2p2.interaction.autosave-failed-has-conflicts",
  /** Autosave: Failed to save assembly "__1__", as it has deleted entities from imports. */
  AutosaveFailedHasDeletions = "b2p2.interaction.autosave-failed-has-deletions",
  /** Autosave: "__1__" saved. */
  AutosaveSucceeded = "b2p2.interaction.autosave-succeeded",
  /** Not in an assembly */
  NoAssemblyHere = "b2p2.interaction.no-assembly-here",
  /** This entity has no (known) source assembly. */
  EntityHasNoSource = "b2p2.interaction.entity-has-no-source",
  /** This entity originates from this assembly. */
  EntityAlreadyAtSource = "b2p2.interaction.entity-already-at-source",
}
export declare const enum L_Gui {
  /** <Unnamed assembly> */
  UnnamedAssembly = "b2p2.gui.unnamed-assembly",
  /** Current assembly: */
  CurrentAssembly = "b2p2.gui.current-assembly",
  /** <None> */
  None = "b2p2.gui.none",
  /** All assemblies */
  AllAssemblies = "b2p2.gui.all-assemblies",
  /** No assemblies */
  NoAssemblies = "b2p2.gui.no-assemblies",
  /** New assembly */
  NewAssembly = "b2p2.gui.new-assembly",
  /** Rename assembly */
  RenameAssembly = "b2p2.gui.rename-assembly",
  /** Cancel rename */
  CancelRenameAssembly = "b2p2.gui.cancel-rename-assembly",
  /** Teleport to assembly */
  TeleportToAssembly = "b2p2.gui.teleport-to-assembly",
  /** Save */
  Save = "b2p2.gui.save",
  /** Save the current assembly and reset the area. */
  SaveButtonTooltip = "b2p2.gui.save-button-tooltip",
  /** There are paste conflicts in this assembly.\nSome entities may not save as expected.\nAre you sure you want to save? */
  ConfirmSaveWithPasteConflicts = "b2p2.gui.confirm-save-with-paste-conflicts",
  /** Some entities from imports have been deleted.\nThese will be re-added when resetting the assembly.\nAre you sure you want to save? */
  ConfirmSaveWithDeletions = "b2p2.gui.confirm-save-with-deletions",
  /** Reset */
  Reset = "b2p2.gui.reset",
  /** Reset the current assembly. [font=default-bold]Shift-click[/font] to skip confirmation dialog. */
  ResetButtonTooltip = "b2p2.gui.reset-button-tooltip",
  /** Are you sure you want to reset this assembly? Any unsaved changes will be lost. */
  ConfirmResetAssembly = "b2p2.gui.confirm-reset-assembly",
  /** Delete assembly */
  DeleteAssembly = "b2p2.gui.delete-assembly",
  /** Are you sure you want to delete the assembly "__1__"? */
  DeleteAssemblyConfirmation = "b2p2.gui.delete-assembly-confirmation",
  /** Imports */
  Imports = "b2p2.gui.imports",
  /** Add import */
  AddImport = "b2p2.gui.add-import",
  /** Choose import source */
  ChooseImportSource = "b2p2.gui.choose-import-source",
  /** There are no importable assemblies. */
  NoSourceAssemblies = "b2p2.gui.no-source-assemblies",
  /** [font=default-bold]Click[/font] to highlight the import.\n[font=default-bold]Control click[/font] to teleport to import source.\n[font=default-bold]Shift click[/font] to move up.\n[font=default-bold]Control-shift click[/font] to move down. */
  ImportItemTooltip = "b2p2.gui.import-item-tooltip",
  /** Delete import */
  DeleteImport = "b2p2.gui.delete-import",
  /** Are you sure you want to delete the import from "__1__"? */
  DeleteImportConfirmation = "b2p2.gui.delete-import-confirmation",
  /** This import no longer exists. */
  ImportNoLongerExists = "b2p2.gui.import-no-longer-exists",
  /** Additional settings */
  LayerAdditionalSettings = "b2p2.gui.layer-additional-settings",
  /** Additional settings: __1__  >  __2__ */
  LayerAdditionalSettingsTitle = "b2p2.gui.layer-additional-settings-title",
  /** Allow upgrades [img=info] */
  LayerAllowUpgrades = "b2p2.gui.layer-allow-upgrades",
  /** Allow upgrades/fast-replace to be affected by blueprinting. */
  LayerAllowUpgradesTooltip = "b2p2.gui.layer-allow-upgrades-tooltip",
  /** Toggle active */
  ToggleImport = "b2p2.gui.toggle-import",
  /** Diagnostics */
  Diagnostics = "b2p2.gui.diagnostics",
  /** Diagnostics [img=warning-white] */
  DiagnosticsWithConflicts = "b2p2.gui.diagnostics-with-conflicts",
  /** Import: __1__ */
  ImportLabel = "b2p2.gui.import-label",
  /** <Own contents> */
  OwnContents = "b2p2.gui.own-contents",
  /** No diagnostics */
  NoDiagnostics = "b2p2.gui.no-diagnostics",
  /** Assemblies */
  AssemblyOverviewTitle = "b2p2.gui.assembly-overview-title",
  /** All assemblies [img=info] */
  AssemblyOverviewCaption = "b2p2.gui.assembly-overview-caption",
  /** [font=default-bold]Click[/font] to open.\n[font=default-bold]Control-click[/font] to teleport to assembly. */
  AssemblyOverviewCaptionTooltip = "b2p2.gui.assembly-overview-caption-tooltip",
  /** Assembly: */
  AssemblyManagerTitle = "b2p2.gui.assembly-manager-title",
}
