// Generated by gen-locale-defs.ts

export declare const enum L_Bbpp {
  /** __1__ from __2__ */
  EntityFromPlace = "bbpp.entity-from-place",
}
export declare const enum L_Diagnostic {
  /** [color=red]Overlaps:[/color] */
  Overlap = "bbpp.diagnostic.overlap",
  /** __1__ overlapped by __2__ */
  OverlapItem = "bbpp.diagnostic.overlap-item",
  /** [color=purple]Upgrades:[/color] */
  CannotUpgrade = "bbpp.diagnostic.cannot-upgrade",
  /** These entities were upgraded/fast-replaced, which cannot be pasted. This may be better supported in the future. */
  CannotUpgradeDetail = "bbpp.diagnostic.cannot-upgrade-detail",
  /** __1__ changed from __2__ */
  CannotUpgradeItem = "bbpp.diagnostic.cannot-upgrade-item",
  /** [color=yellow]Item requests ignored:[/color] */
  ItemsIgnored = "bbpp.diagnostic.items-ignored",
  /** Changes in item requests will have no effect on paste. */
  ItemsIgnoredDetail = "bbpp.diagnostic.items-ignored-detail",
  /** __1__ */
  ItemsIgnoredItem = "bbpp.diagnostic.items-ignored-item",
  /** [color=yellow]Unsupported properties:[/color] */
  UnsupportedProp = "bbpp.diagnostic.unsupported-prop",
  /** These properties are not yet checked. Please report this to the mod author! */
  UnsupportedPropDetail = "bbpp.diagnostic.unsupported-prop-detail",
  /** __1__: "__2__" not supported */
  UnsupportedPropItem = "bbpp.diagnostic.unsupported-prop-item",
  /** [color=red]The import "__1__" is no longer valid.[/color] */
  InvalidImport = "bbpp.diagnostic.invalid-import",
}
export declare const enum L_Interaction {
  /** An unexpected error occurred: __1__. Additional details outputted to log. Please report this to the mod author! */
  UnexpectedError = "bbpp.interaction.unexpected-error",
  /** Could not clear cursor */
  CannotClearCursor = "bbpp.interaction.cannot-clear-cursor",
  /** Select an area for the new assembly */
  SelectAreaForAssembly = "bbpp.interaction.select-area-for-assembly",
  /** This area intersects with an existing assembly: __1__ */
  IntersectsExistingAssembly = "bbpp.interaction.intersects-existing-assembly",
  /** The import does not intersect with the target assembly at this location. */
  ImportDoesNotIntersectAssembly = "bbpp.interaction.import-does-not-intersect-assembly",
  /** The source or target assembly no longer exists. */
  ImportNoLongerValid = "bbpp.interaction.import-no-longer-valid",
  /** Flipped or rotated imports are currently not supported. */
  CannotFlipOrRotateImport = "bbpp.interaction.cannot-flip-or-rotate-import",
  /** An import from "__1__" was created on "__2__". */
  ImportCreated = "bbpp.interaction.import-created",
  /** Assembly saved\n  [font=default-bold]__1__[/font] entities */
  AssemblySaved = "bbpp.interaction.assembly-saved",
  /** Paste conflicts found after reset! */
  FoundPasteConflicts = "bbpp.interaction.found-paste-conflicts",
  /** Cannot open map view on a different surface. Try going into editor mode. */
  CannotOpenMapOnDifferentSurface = "bbpp.interaction.cannot-open-map-on-different-surface",
  /** __1__ */
  TranslateDialogueMessage = "bbpp.interaction.translate-dialogue-message",
}
export declare const enum L_Gui {
  /** <Unnamed assembly> */
  UnnamedAssembly = "bbpp.gui.unnamed-assembly",
  /** Rename assembly */
  RenameAssembly = "bbpp.gui.rename-assembly",
  /** Cancel rename */
  CancelRenameAssembly = "bbpp.gui.cancel-rename-assembly",
  /** Teleport to assembly */
  TeleportToAssembly = "bbpp.gui.teleport-to-assembly",
  /** Save */
  Save = "bbpp.gui.save",
  /** Save the current assembly, and reset the area. */
  SaveButtonTooltip = "bbpp.gui.save-button-tooltip",
  /** There are paste conflicts in this assembly.\nSome entities may not save as expected.\nAre you sure you want to save? */
  ConfirmSaveWithPasteConflicts = "bbpp.gui.confirm-save-with-paste-conflicts",
  /** Some entities from imports have been deleted.\nThese will be re-added when resetting the assembly.\nAre you sure you want to save? */
  ConfirmSaveWithDeletions = "bbpp.gui.confirm-save-with-deletions",
  /** Reset */
  Reset = "bbpp.gui.reset",
  /** Resets the current assembly. [font=default-bold]Shift-click[/font] to skip confirmation dialog. */
  ResetButtonTooltip = "bbpp.gui.reset-button-tooltip",
  /** Are you sure you want to reset this assembly? Any unsaved changes will be lost. */
  ConfirmResetAssembly = "bbpp.gui.confirm-reset-assembly",
  /** Delete assembly */
  DeleteAssembly = "bbpp.gui.delete-assembly",
  /** Are you sure you want to delete the assembly "__1__"? */
  DeleteAssemblyConfirmation = "bbpp.gui.delete-assembly-confirmation",
  /** Imports */
  Imports = "bbpp.gui.imports",
  /** Add import */
  AddImport = "bbpp.gui.add-import",
  /** Choose import source */
  ChooseImportSource = "bbpp.gui.choose-import-source",
  /** There are no importable assemblies. */
  NoSourceAssemblies = "bbpp.gui.no-source-assemblies",
  /** Delete import */
  DeleteImport = "bbpp.gui.delete-import",
  /** Are you sure you want to delete the import from "__1__"? */
  DeleteImportConfirmation = "bbpp.gui.delete-import-confirmation",
  /** This import no longer exists. */
  ImportNoLongerExists = "bbpp.gui.import-no-longer-exists",
  /** Diagnostics */
  Diagnostics = "bbpp.gui.diagnostics",
  /** Diagnostics [img=warning-white] */
  DiagnosticsWithConflicts = "bbpp.gui.diagnostics-with-conflicts",
  /** Import: __1__ */
  ImportLabel = "bbpp.gui.import-label",
  /** <Own contents> */
  OwnContents = "bbpp.gui.own-contents",
  /** No diagnostics */
  NoDiagnostics = "bbpp.gui.no-diagnostics",
  /** Assemblies */
  AssemblyOverviewTitle = "bbpp.gui.assembly-overview-title",
  /** All assemblies [img=info] */
  AssemblyOverviewCaption = "bbpp.gui.assembly-overview-caption",
  /** [font=default-bold]Click[/font] to open.\n[font=default-bold]Control-click[/font] to teleport to assembly. */
  AssemblyOverviewCaptionTooltip = "bbpp.gui.assembly-overview-caption-tooltip",
  /** No assemblies */
  NoAssemblies = "bbpp.gui.no-assemblies",
  /** New assembly */
  NewAssembly = "bbpp.gui.new-assembly",
  /** Assembly: */
  AssemblyManagerTitle = "bbpp.gui.assembly-manager-title",
}
