// This file was auto-generated by scripts\generateGuiSpecs.ts. Do not edit directly!

import { MaybeSource } from "../callbags"

export interface BaseElementSpec {
  type: GuiElementType
  name?: MaybeSource<string>
  caption?: MaybeSource<LocalisedString>
  tooltip?: MaybeSource<LocalisedString>
  enabled?: MaybeSource<boolean>
  visible?: MaybeSource<boolean>
  ignored_by_interaction?: MaybeSource<boolean>
  style?: string
  tags?: MaybeSource<Tags>
  anchor?: MaybeSource<GuiAnchor | undefined>
  location?: MaybeSource<GuiLocation | undefined>
  children?: ElementSpec[]
}

export interface ChooseElemButtonElementSpec extends BaseElementSpec {
  type: "choose-elem-button"
  elem_type: ChooseElemButtonType
  elem_filters?: MaybeSource<ChooseElemButtonFilters[this["elem_type"]] | undefined>
  elem_value?: MaybeSource<(this["elem_type"] extends "signal" ? SignalID : string) | undefined>
  locked?: MaybeSource<boolean>
  children?: ElementSpec[]
}

export interface DropDownElementSpec extends BaseElementSpec {
  type: "drop-down"
  items?: MaybeSource<LocalisedString[]>
  selected_index?: MaybeSource<uint>
  children?: ElementSpec[]
}

export interface EmptyWidgetElementSpec extends BaseElementSpec {
  type: "empty-widget"
  drag_target?: MaybeSource<LuaGuiElement | undefined>
  children?: ElementSpec[]
}

export interface EntityPreviewElementSpec extends BaseElementSpec {
  type: "entity-preview"
  entity?: MaybeSource<LuaEntity | undefined>
  children?: ElementSpec[]
}

export interface ListBoxElementSpec extends BaseElementSpec {
  type: "list-box"
  items?: MaybeSource<LocalisedString[]>
  selected_index?: MaybeSource<uint>
  children?: ElementSpec[]
}

export interface ScrollPaneElementSpec extends BaseElementSpec {
  type: "scroll-pane"
  horizontal_scroll_policy?: MaybeSource<
    "auto" | "never" | "always" | "auto-and-reserve-space" | "dont-show-but-allow-scrolling"
  >
  vertical_scroll_policy?: MaybeSource<
    "auto" | "never" | "always" | "auto-and-reserve-space" | "dont-show-but-allow-scrolling"
  >
  children?: ElementSpec[]
}

export interface SpriteButtonElementSpec extends BaseElementSpec {
  type: "sprite-button"
  sprite?: MaybeSource<SpritePath>
  hovered_sprite?: MaybeSource<SpritePath>
  clicked_sprite?: MaybeSource<SpritePath>
  number?: MaybeSource<double | undefined>
  show_percent_for_small_numbers?: MaybeSource<boolean>
  mouse_button_filter?: MaybeSource<MouseButtonFlags>
  children?: ElementSpec[]
}

export interface TabbedPaneElementSpec extends BaseElementSpec {
  type: "tabbed-pane"
  selected_tab_index?: MaybeSource<uint | undefined>
  children?: ElementSpec[]
}

export interface TextBoxElementSpec extends BaseElementSpec {
  type: "text-box"
  text?: MaybeSource<string>
  clear_and_focus_on_right_click?: MaybeSource<boolean>
  selectable?: MaybeSource<boolean>
  word_wrap?: MaybeSource<boolean>
  read_only?: MaybeSource<boolean>
  children?: ElementSpec[]
}

export interface ButtonElementSpec extends BaseElementSpec {
  type: "button"
  mouse_button_filter?: MaybeSource<MouseButtonFlags>
  children?: ElementSpec[]
}

export interface CameraElementSpec extends BaseElementSpec {
  type: "camera"
  position: MaybeSource<Position>
  surface_index?: MaybeSource<uint>
  zoom?: MaybeSource<double>
  entity?: MaybeSource<LuaEntity | undefined>
  children?: ElementSpec[]
}

export interface CheckboxElementSpec extends BaseElementSpec {
  type: "checkbox"
  state: MaybeSource<boolean>
  children?: ElementSpec[]
}

export interface FlowElementSpec extends BaseElementSpec {
  type: "flow"
  direction?: "horizontal" | "vertical"
  drag_target?: MaybeSource<LuaGuiElement | undefined>
  children?: ElementSpec[]
}

export interface FrameElementSpec extends BaseElementSpec {
  type: "frame"
  direction?: "horizontal" | "vertical"
  auto_center?: MaybeSource<boolean>
  drag_target?: MaybeSource<LuaGuiElement | undefined>
  children?: ElementSpec[]
}

export interface LabelElementSpec extends BaseElementSpec {
  type: "label"
  drag_target?: MaybeSource<LuaGuiElement | undefined>
  children?: ElementSpec[]
}

export interface LineElementSpec extends BaseElementSpec {
  type: "line"
  direction?: "horizontal" | "vertical"
  children?: ElementSpec[]
}

export interface MinimapElementSpec extends BaseElementSpec {
  type: "minimap"
  position?: MaybeSource<Position>
  surface_index?: MaybeSource<uint>
  chart_player_index?: uint
  force?: MaybeSource<string | undefined>
  zoom?: MaybeSource<double>
  minimap_player_index?: MaybeSource<uint>
  entity?: MaybeSource<LuaEntity | undefined>
  children?: ElementSpec[]
}

export interface ProgressBarElementSpec extends BaseElementSpec {
  type: "progressbar"
  value?: MaybeSource<double>
  children?: ElementSpec[]
}

export interface RadioButtonElementSpec extends BaseElementSpec {
  type: "radiobutton"
  state: MaybeSource<boolean>
  children?: ElementSpec[]
}

export interface SliderElementSpec extends BaseElementSpec {
  type: "slider"
  minimum_value?: MaybeSource<double>
  maximum_value?: MaybeSource<double>
  value_step?: MaybeSource<double>
  discrete_slider?: MaybeSource<double>
  discrete_values?: boolean
  slider_value?: MaybeSource<double>
  discrete_value?: MaybeSource<double>
  children?: ElementSpec[]
}

export interface SpriteElementSpec extends BaseElementSpec {
  type: "sprite"
  sprite?: MaybeSource<SpritePath>
  resize_to_sprite?: MaybeSource<boolean>
  children?: ElementSpec[]
}

export interface SwitchElementSpec extends BaseElementSpec {
  type: "switch"
  switch_state?: MaybeSource<string>
  allow_none_state?: MaybeSource<boolean>
  left_label_caption?: MaybeSource<LocalisedString>
  left_label_tooltip?: MaybeSource<LocalisedString>
  right_label_caption?: MaybeSource<LocalisedString>
  right_label_tooltip?: MaybeSource<LocalisedString>
  children?: ElementSpec[]
}

export interface TabElementSpec extends BaseElementSpec {
  type: "tab"
  badge_text?: MaybeSource<LocalisedString>
  children?: ElementSpec[]
}

export interface TableElementSpec extends BaseElementSpec {
  type: "table"
  column_count: uint
  draw_vertical_lines?: MaybeSource<boolean>
  draw_horizontal_lines?: MaybeSource<boolean>
  draw_horizontal_line_after_headers?: MaybeSource<boolean>
  vertical_centering?: MaybeSource<boolean>
  drag_target?: MaybeSource<LuaGuiElement | undefined>
  children?: ElementSpec[]
}

export interface TextFieldElementSpec extends BaseElementSpec {
  type: "textfield"
  text?: MaybeSource<string>
  numeric?: MaybeSource<boolean>
  allow_decimal?: MaybeSource<boolean>
  allow_negative?: MaybeSource<boolean>
  is_password?: MaybeSource<boolean>
  lose_focus_on_confirm?: MaybeSource<boolean>
  clear_and_focus_on_right_click?: MaybeSource<boolean>
  children?: ElementSpec[]
}

export type ElementSpec =
  | ChooseElemButtonElementSpec
  | DropDownElementSpec
  | EmptyWidgetElementSpec
  | EntityPreviewElementSpec
  | ListBoxElementSpec
  | ScrollPaneElementSpec
  | SpriteButtonElementSpec
  | TabbedPaneElementSpec
  | TextBoxElementSpec
  | ButtonElementSpec
  | CameraElementSpec
  | CheckboxElementSpec
  | FlowElementSpec
  | FrameElementSpec
  | LabelElementSpec
  | LineElementSpec
  | MinimapElementSpec
  | ProgressBarElementSpec
  | RadioButtonElementSpec
  | SliderElementSpec
  | SpriteElementSpec
  | SwitchElementSpec
  | TabElementSpec
  | TableElementSpec
  | TextFieldElementSpec
