export default {
  "choose-elem-button": {
    type: ["type"],
    name: ["name", "name"],
    caption: ["caption", "caption"],
    tooltip: ["tooltip", "tooltip"],
    enabled: ["enabled", "enabled"],
    visible: ["visible", "visible"],
    ignored_by_interaction: ["ignored_by_interaction", "ignored_by_interaction"],
    style: ["style"],
    tags: ["tags", "tags"],
    anchor: ["anchor", "anchor"],
    elem_type: ["elem_type"],
    elem_filters: ["filters", "elem_filters"],
    location: [undefined, "location"],
    elem_value: [undefined, "elem_value"],
    locked: [undefined, "locked"],
  },
  "drop-down": {
    type: ["type"],
    name: ["name", "name"],
    caption: ["caption", "caption"],
    tooltip: ["tooltip", "tooltip"],
    enabled: ["enabled", "enabled"],
    visible: ["visible", "visible"],
    ignored_by_interaction: ["ignored_by_interaction", "ignored_by_interaction"],
    style: ["style"],
    tags: ["tags", "tags"],
    anchor: ["anchor", "anchor"],
    items: ["items", "items"],
    selected_index: ["selected_index", "selected_index"],
    location: [undefined, "location"],
  },
  "empty-widget": {
    type: ["type"],
    name: ["name", "name"],
    caption: ["caption", "caption"],
    tooltip: ["tooltip", "tooltip"],
    enabled: ["enabled", "enabled"],
    visible: ["visible", "visible"],
    ignored_by_interaction: ["ignored_by_interaction", "ignored_by_interaction"],
    style: ["style"],
    tags: ["tags", "tags"],
    anchor: ["anchor", "anchor"],
    location: [undefined, "location"],
    drag_target: [undefined, "drag_target"],
  },
  "entity-preview": {
    type: ["type"],
    name: ["name", "name"],
    caption: ["caption", "caption"],
    tooltip: ["tooltip", "tooltip"],
    enabled: ["enabled", "enabled"],
    visible: ["visible", "visible"],
    ignored_by_interaction: ["ignored_by_interaction", "ignored_by_interaction"],
    style: ["style"],
    tags: ["tags", "tags"],
    anchor: ["anchor", "anchor"],
    location: [undefined, "location"],
    entity: [undefined, "entity"],
  },
  "list-box": {
    type: ["type"],
    name: ["name", "name"],
    caption: ["caption", "caption"],
    tooltip: ["tooltip", "tooltip"],
    enabled: ["enabled", "enabled"],
    visible: ["visible", "visible"],
    ignored_by_interaction: ["ignored_by_interaction", "ignored_by_interaction"],
    style: ["style"],
    tags: ["tags", "tags"],
    anchor: ["anchor", "anchor"],
    items: ["items", "items"],
    selected_index: ["selected_index", "selected_index"],
    location: [undefined, "location"],
  },
  "scroll-pane": {
    type: ["type"],
    name: ["name", "name"],
    caption: ["caption", "caption"],
    tooltip: ["tooltip", "tooltip"],
    enabled: ["enabled", "enabled"],
    visible: ["visible", "visible"],
    ignored_by_interaction: ["ignored_by_interaction", "ignored_by_interaction"],
    style: ["style"],
    tags: ["tags", "tags"],
    anchor: ["anchor", "anchor"],
    horizontal_scroll_policy: ["horizontal_scroll_policy", "horizontal_scroll_policy"],
    vertical_scroll_policy: ["vertical_scroll_policy", "vertical_scroll_policy"],
    location: [undefined, "location"],
  },
  "sprite-button": {
    type: ["type"],
    name: ["name", "name"],
    caption: ["caption", "caption"],
    tooltip: ["tooltip", "tooltip"],
    enabled: ["enabled", "enabled"],
    visible: ["visible", "visible"],
    ignored_by_interaction: ["ignored_by_interaction", "ignored_by_interaction"],
    style: ["style"],
    tags: ["tags", "tags"],
    anchor: ["anchor", "anchor"],
    sprite: ["sprite", "sprite"],
    hovered_sprite: ["hovered_sprite", "hovered_sprite"],
    clicked_sprite: ["clicked_sprite", "clicked_sprite"],
    number: ["number", "number"],
    show_percent_for_small_numbers: ["show_percent_for_small_numbers", "show_percent_for_small_numbers"],
    mouse_button_filter: ["mouse_button_filter", "mouse_button_filter"],
    location: [undefined, "location"],
    resize_to_sprite: [undefined, "resize_to_sprite"],
  },
  "tabbed-pane": {
    type: ["type"],
    name: ["name", "name"],
    caption: ["caption", "caption"],
    tooltip: ["tooltip", "tooltip"],
    enabled: ["enabled", "enabled"],
    visible: ["visible", "visible"],
    ignored_by_interaction: ["ignored_by_interaction", "ignored_by_interaction"],
    style: ["style"],
    tags: ["tags", "tags"],
    anchor: ["anchor", "anchor"],
    location: [undefined, "location"],
    selected_tab_index: [undefined, "selected_tab_index"],
  },
  "text-box": {
    type: ["type"],
    name: ["name", "name"],
    caption: ["caption", "caption"],
    tooltip: ["tooltip", "tooltip"],
    enabled: ["enabled", "enabled"],
    visible: ["visible", "visible"],
    ignored_by_interaction: ["ignored_by_interaction", "ignored_by_interaction"],
    style: ["style"],
    tags: ["tags", "tags"],
    anchor: ["anchor", "anchor"],
    text: ["text", "text"],
    clear_and_focus_on_right_click: ["clear_and_focus_on_right_click", "clear_and_focus_on_right_click"],
    location: [undefined, "location"],
    selectable: [undefined, "selectable"],
    word_wrap: [undefined, "word_wrap"],
    read_only: [undefined, "read_only"],
  },
  button: {
    type: ["type"],
    name: ["name", "name"],
    caption: ["caption", "caption"],
    tooltip: ["tooltip", "tooltip"],
    enabled: ["enabled", "enabled"],
    visible: ["visible", "visible"],
    ignored_by_interaction: ["ignored_by_interaction", "ignored_by_interaction"],
    style: ["style"],
    tags: ["tags", "tags"],
    anchor: ["anchor", "anchor"],
    mouse_button_filter: ["mouse_button_filter", "mouse_button_filter"],
    location: [undefined, "location"],
  },
  camera: {
    type: ["type"],
    name: ["name", "name"],
    caption: ["caption", "caption"],
    tooltip: ["tooltip", "tooltip"],
    enabled: ["enabled", "enabled"],
    visible: ["visible", "visible"],
    ignored_by_interaction: ["ignored_by_interaction", "ignored_by_interaction"],
    style: ["style"],
    tags: ["tags", "tags"],
    anchor: ["anchor", "anchor"],
    position: ["position", "position"],
    surface_index: ["surface_index", "surface_index"],
    zoom: ["zoom", "zoom"],
    location: [undefined, "location"],
    entity: [undefined, "entity"],
  },
  checkbox: {
    type: ["type"],
    name: ["name", "name"],
    caption: ["caption", "caption"],
    tooltip: ["tooltip", "tooltip"],
    enabled: ["enabled", "enabled"],
    visible: ["visible", "visible"],
    ignored_by_interaction: ["ignored_by_interaction", "ignored_by_interaction"],
    style: ["style"],
    tags: ["tags", "tags"],
    anchor: ["anchor", "anchor"],
    state: ["state", "state"],
    location: [undefined, "location"],
  },
  flow: {
    type: ["type"],
    name: ["name", "name"],
    caption: ["caption", "caption"],
    tooltip: ["tooltip", "tooltip"],
    enabled: ["enabled", "enabled"],
    visible: ["visible", "visible"],
    ignored_by_interaction: ["ignored_by_interaction", "ignored_by_interaction"],
    style: ["style"],
    tags: ["tags", "tags"],
    anchor: ["anchor", "anchor"],
    direction: ["direction"],
    location: [undefined, "location"],
    drag_target: [undefined, "drag_target"],
  },
  frame: {
    type: ["type"],
    name: ["name", "name"],
    caption: ["caption", "caption"],
    tooltip: ["tooltip", "tooltip"],
    enabled: ["enabled", "enabled"],
    visible: ["visible", "visible"],
    ignored_by_interaction: ["ignored_by_interaction", "ignored_by_interaction"],
    style: ["style"],
    tags: ["tags", "tags"],
    anchor: ["anchor", "anchor"],
    direction: ["direction"],
    location: [undefined, "location"],
    auto_center: [undefined, "auto_center"],
    drag_target: [undefined, "drag_target"],
  },
  label: {
    type: ["type"],
    name: ["name", "name"],
    caption: ["caption", "caption"],
    tooltip: ["tooltip", "tooltip"],
    enabled: ["enabled", "enabled"],
    visible: ["visible", "visible"],
    ignored_by_interaction: ["ignored_by_interaction", "ignored_by_interaction"],
    style: ["style"],
    tags: ["tags", "tags"],
    anchor: ["anchor", "anchor"],
    location: [undefined, "location"],
    drag_target: [undefined, "drag_target"],
  },
  line: {
    type: ["type"],
    name: ["name", "name"],
    caption: ["caption", "caption"],
    tooltip: ["tooltip", "tooltip"],
    enabled: ["enabled", "enabled"],
    visible: ["visible", "visible"],
    ignored_by_interaction: ["ignored_by_interaction", "ignored_by_interaction"],
    style: ["style"],
    tags: ["tags", "tags"],
    anchor: ["anchor", "anchor"],
    direction: ["direction"],
    location: [undefined, "location"],
  },
  minimap: {
    type: ["type"],
    name: ["name", "name"],
    caption: ["caption", "caption"],
    tooltip: ["tooltip", "tooltip"],
    enabled: ["enabled", "enabled"],
    visible: ["visible", "visible"],
    ignored_by_interaction: ["ignored_by_interaction", "ignored_by_interaction"],
    style: ["style"],
    tags: ["tags", "tags"],
    anchor: ["anchor", "anchor"],
    position: ["position", "position"],
    surface_index: ["surface_index", "surface_index"],
    chart_player_index: ["chart_player_index"],
    force: ["force", "force"],
    zoom: ["zoom", "zoom"],
    location: [undefined, "location"],
    minimap_player_index: [undefined, "minimap_player_index"],
    entity: [undefined, "entity"],
  },
  progressbar: {
    type: ["type"],
    name: ["name", "name"],
    caption: ["caption", "caption"],
    tooltip: ["tooltip", "tooltip"],
    enabled: ["enabled", "enabled"],
    visible: ["visible", "visible"],
    ignored_by_interaction: ["ignored_by_interaction", "ignored_by_interaction"],
    style: ["style"],
    tags: ["tags", "tags"],
    anchor: ["anchor", "anchor"],
    value: ["value", "value"],
    location: [undefined, "location"],
  },
  radiobutton: {
    type: ["type"],
    name: ["name", "name"],
    caption: ["caption", "caption"],
    tooltip: ["tooltip", "tooltip"],
    enabled: ["enabled", "enabled"],
    visible: ["visible", "visible"],
    ignored_by_interaction: ["ignored_by_interaction", "ignored_by_interaction"],
    style: ["style"],
    tags: ["tags", "tags"],
    anchor: ["anchor", "anchor"],
    state: ["state", "state"],
    location: [undefined, "location"],
  },
  slider: {
    type: ["type"],
    name: ["name", "name"],
    caption: ["caption", "caption"],
    tooltip: ["tooltip", "tooltip"],
    enabled: ["enabled", "enabled"],
    visible: ["visible", "visible"],
    ignored_by_interaction: ["ignored_by_interaction", "ignored_by_interaction"],
    style: ["style"],
    tags: ["tags", "tags"],
    anchor: ["anchor", "anchor"],
    minimum_value: ["minimum_value"],
    maximum_value: ["maximum_value"],
    value: ["value"],
    value_step: ["value_step"],
    discrete_slider: ["discrete_slider"],
    discrete_values: ["discrete_values"],
    location: [undefined, "location"],
    slider_value: [undefined, "slider_value"],
  },
  sprite: {
    type: ["type"],
    name: ["name", "name"],
    caption: ["caption", "caption"],
    tooltip: ["tooltip", "tooltip"],
    enabled: ["enabled", "enabled"],
    visible: ["visible", "visible"],
    ignored_by_interaction: ["ignored_by_interaction", "ignored_by_interaction"],
    style: ["style"],
    tags: ["tags", "tags"],
    anchor: ["anchor", "anchor"],
    sprite: ["sprite", "sprite"],
    resize_to_sprite: ["resize_to_sprite", "resize_to_sprite"],
    location: [undefined, "location"],
  },
  switch: {
    type: ["type"],
    name: ["name", "name"],
    caption: ["caption", "caption"],
    tooltip: ["tooltip", "tooltip"],
    enabled: ["enabled", "enabled"],
    visible: ["visible", "visible"],
    ignored_by_interaction: ["ignored_by_interaction", "ignored_by_interaction"],
    style: ["style"],
    tags: ["tags", "tags"],
    anchor: ["anchor", "anchor"],
    switch_state: ["switch_state", "switch_state"],
    allow_none_state: ["allow_none_state", "allow_none_state"],
    left_label_caption: ["left_label_caption", "left_label_caption"],
    left_label_tooltip: ["left_label_tooltip", "left_label_tooltip"],
    right_label_caption: ["right_label_caption", "right_label_caption"],
    right_label_tooltip: ["right_label_tooltip", "right_label_tooltip"],
    location: [undefined, "location"],
  },
  tab: {
    type: ["type"],
    name: ["name", "name"],
    caption: ["caption", "caption"],
    tooltip: ["tooltip", "tooltip"],
    enabled: ["enabled", "enabled"],
    visible: ["visible", "visible"],
    ignored_by_interaction: ["ignored_by_interaction", "ignored_by_interaction"],
    style: ["style"],
    tags: ["tags", "tags"],
    anchor: ["anchor", "anchor"],
    badge_text: ["badge_text", "badge_text"],
    location: [undefined, "location"],
  },
  table: {
    type: ["type"],
    name: ["name", "name"],
    caption: ["caption", "caption"],
    tooltip: ["tooltip", "tooltip"],
    enabled: ["enabled", "enabled"],
    visible: ["visible", "visible"],
    ignored_by_interaction: ["ignored_by_interaction", "ignored_by_interaction"],
    style: ["style"],
    tags: ["tags", "tags"],
    anchor: ["anchor", "anchor"],
    column_count: ["column_count"],
    draw_vertical_lines: ["draw_vertical_lines", "draw_vertical_lines"],
    draw_horizontal_lines: ["draw_horizontal_lines", "draw_horizontal_lines"],
    draw_horizontal_line_after_headers: ["draw_horizontal_line_after_headers", "draw_horizontal_line_after_headers"],
    vertical_centering: ["vertical_centering", "vertical_centering"],
    location: [undefined, "location"],
    drag_target: [undefined, "drag_target"],
  },
  textfield: {
    type: ["type"],
    name: ["name", "name"],
    caption: ["caption", "caption"],
    tooltip: ["tooltip", "tooltip"],
    enabled: ["enabled", "enabled"],
    visible: ["visible", "visible"],
    ignored_by_interaction: ["ignored_by_interaction", "ignored_by_interaction"],
    style: ["style"],
    tags: ["tags", "tags"],
    anchor: ["anchor", "anchor"],
    text: ["text", "text"],
    numeric: ["numeric", "numeric"],
    allow_decimal: ["allow_decimal", "allow_decimal"],
    allow_negative: ["allow_negative", "allow_negative"],
    is_password: ["is_password", "is_password"],
    lose_focus_on_confirm: ["lose_focus_on_confirm", "lose_focus_on_confirm"],
    clear_and_focus_on_right_click: ["clear_and_focus_on_right_click", "clear_and_focus_on_right_click"],
    location: [undefined, "location"],
  },
}
